### ISSUE TITLE
Bylaws

### ISSUE THREAD

**Issue by kthull** [mosa-chicago/mosa#12]
The copypasta of bylaws was suitable to create the nonprofit entity, but is rife with unnecessary legalese so we agreed to update them at our last meeting. See #mosa slack backscroll for links, or wholly accept @zendoodles draft rewrite. 

Also need to consider some of the questions raised in the #mosa channel dgorton https://midcamp.slack.com/archives/CCCUB3FA9/p1537539990000100
> but i’d want to start by asking big PITA questions: why, mission clarity, audience clarity, governance, succession plans, etc.

Proposed updated bylaws: https://docs.google.com/document/d/1XUbyaP3ipz-RcYlr19Fefq52TBWrCXcULEpuXhQuLWc/edit#

**Comment by zendoodles** [comment]
I would also consider adding a simple code of conduct to the bylaws.

I propose we send appropriate announcements and vote on the above proposed updated bylaws ASAP.  Once more manageable bylaws are in place, we can more easily make amendments to address any of the other questions/concerns at a later date.

Unfortunately, just calling a meeting to approve the less cumbersome bylaws is going to take some doing...

> The bylaws may be amended, altered, or repealed by the Board of Directors by a majority of a quorum vote at any regular or special meeting. The text of the proposed change shall be distributed to all board members at least ten (10) days before the meeting.

> Special meetings may be requested by the President, Vice-President, Secretary, or any two directors by providing five days’ written notice by ordinary United States mail, effective when mailed. Minutes of the meeting shall be sent to the Board of Directors within two weeks after the meeting.

> Written notice of all meetings shall be provided under this section or as otherwise required by law. The Notice shall state the place, date, and hour of meeting, and if for a special meeting, the purpose of the meeting. Such notice shall be mailed to all directors of record at the address shown on the corporate books, at least 10 days prior to the meeting, or 20 days if removing a director. Such notice shall be deemed effective when deposited in ordinary U.S. mail, properly addressed, with postage prepaid.

...and (sorry @froboy)
> Secretary. The Secretary shall give notice of all meetings of the Board of Directors and Executive Committee, shall keep an accurate list of the directors, and shall have the authority to certify any records, or copies of records, as the official records of the organization. The Secretary shall maintain the minutes of the Board of Directors' meetings and all committee meetings.

**Comment by kthull** [comment]
We also need to define and add in at-large board members

**Comment by kthull** [comment]
The main issue is complete. Created a new issue for at-large board members: https://github.com/mosa-chicago/mosa/issues/35
