### ISSUE TITLE
Evaluate whether we should keep Aplos or find an alternate

### ISSUE THREAD

**Issue by zendoodles** [mosa-chicago/mosa#14]
I'm currently in a trial period for QuickBooks. It looks like it will maybe do the trick. Questions:

- [ ] Reporting/budgeting for individual events (funds)?
- [ ] Separate logins for event/fund users?
- [ ] Tax forms?
- [ ] Can we replace square with it? (I think so)
- [ ] Do we gaf about donor management?

**Comment by kthull** [comment]
We have migrated to quickbooks already so closing this.
