### ISSUE TITLE
Evaluate donations via Humble Bundle, Amazon Smile, etc.

### ISSUE THREAD

**Issue by JDDoesDev** [mosa-chicago/mosa#21]
Need to check and see what the process is for becoming a part of the Amazon Smile, Humble Bundle, eBay charity, etc. donation process.

**Comment by davidneedham** [comment]
[This article on the Humble Bundle site](https://support.humblebundle.com/hc/en-us/articles/204303548-Requesting-to-be-a-Featured-Charity-for-Humble-Bundle) says that we need to become a [PayPal Giving Fund](https://www.paypal.com/us/webapps/mpp/givingfund/home) charity. Bonus, that's also how we get listed as an eBay charity.
