### ISSUE TITLE
Illinois Annual Report

### ISSUE THREAD

**Issue by froboy** [mosa-chicago/mosa#24]
FYI, we got a reminder from the Secretary of State about needing to submit out annual report by July 1.

**Comment by kthull** [comment]
https://drive.google.com/file/d/15EMHHA_KUk5-4vBtakFb62Rtcc5ec_A0/view?usp=drivesdk

**Comment by kthull** [comment]
Received mailing for 2020 annual report filing due by July 1, 2020

**Comment by kthull** [comment]
Filed with update to board of directors: https://drive.google.com/open?id=1TTIcl60Dj00Yzzg7ZUF65ywcVknuWK0z

- removal of vice president
- updated address for Avi
