### ISSUE TITLE
Open Call for MOSA Board Member

### ISSUE THREAD

**Issue by froboy** [mosa-chicago/mosa#31]
The Midwest Open Source Alliance is seeking self-nominations to fill our Vice President board position. 

VP responsibilities can be found in the [Officers section of our bylaws](https://docs.google.com/document/d/e/2PACX-1vQHAkp3QHmniPAmzhEpVNTyTTX5SkTuvq8fuL4k8wWJp17te3rCEuxVNgJaVGspJrwg726AiXBIJoIh/pub#h.vi1he7kq67pp). In practice, this consists of attending monthly meetings and assisting with decisions on our Slack team. 

Anyone involved in an open-source project or related event is eligible to join. _No technical skills are required._ The ideal board member would be connected to other open source communities, and either have experience with logistics in small non-profits or a desire to learn them.

To express your interest, please comment on this issue by Monday, June 29, 2020 with your name and organization. We will select a nominee by vote at our annual meeting, Tuesday, June 30.

**Comment by cdchris12** [comment]
I'd like to throw my hat in the ring for consideration. In my day job at amazee.io, I'm a maintainer of the open source project [Lagoon](https://github.com/amazeeio/lagoon), and I'm a staunch supporter of open source technologies. If I can be of assistance in this position, I'd be delighted to help however I can. :)

You can read more about me on [GitHub](https://github.com/cdchris12), Twitter(https://twitter.com/cdchris12), and/or LinkedIn(https://www.linkedin.com/in/cdchris12/) if you'd like.

**Comment by RobertJacobiCom** [comment]
MOSA and Avi,

I am an independent consultant in the open source arena perviously running a successful digital agency as well as advising as executive with a startup acquired last year by WP Engine. I focus on open source, content management, SaaS, and hosting. My major previous non-profit experience is as President of Open Source Matters, the legal entity for Joomla. I would be happy to be included for consideration.

Regards,

Robert

**Comment by mathuaerknedam** [comment]
I'll volunteer as well. I'm currently a sysadmin for University of Illinois, formerly for open source developer The HDF Group, a developer for Adium, and I've served on the board for Instant Messaging Freedom as VP the last four years. Due to a variety of factors, my VP duties have included a "pseudo" vice-treasurer role.

Matthew Needham

**Comment by froboy** [comment]
@cdchris12 @RobertJacobiCom @mathuaerknedam Thanks for your interest! Please join us tomorrow night at 7PM if you’re able. All are welcome and while there’s only one official vacant seat, we’re totally open to getting more folks involved in other capacities. Meeting details in Slack.

**Comment by froboy** [comment]
@RobertJacobiCom @cdchris12 @mathuaerknedam Thank you all very much for your time. 

Robert was elected unanimously as VP of MOSA.
