### ISSUE TITLE
Meeting schedule

### ISSUE THREAD

**Issue by kthull** [mosa-chicago/mosa#5]
We should schedule out quarterlies

**Comment by zendoodles** [comment]
IMO we should schedule more than quarterly until we get the bylaws updated and the @todo list to a manageable place.

@kthull @froboy @JDDoesDev How about the weeks we're not doing midcamp meetings for a bit? What days/times work for you?

**Comment by froboy** [comment]
I think we could do a lot of this in Slack, but maybe having 30min bi-weekly would help keep things going. We could even have a quick check-in and then just make it a co-working session for efficiency.

**Comment by kthull** [comment]
Works for me. Tuesday through Thursday work best to avoid possible camp travel. I'm cool doing it over whatever qualifies as lunchtime for normal people.

**Comment by JDDoesDev** [comment]
I'm good with whatever.  Slack/virtual work best for me depending on the day of the week
